-- CreateTable
CREATE TABLE "Call" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "callActive" BOOLEAN NOT NULL DEFAULT true,
    "callAnswered" BOOLEAN NOT NULL DEFAULT false,
    "CallDateTime" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ResidentID" INTEGER NOT NULL,
    CONSTRAINT "Call_ResidentID_fkey" FOREIGN KEY ("ResidentID") REFERENCES "Resident" ("id") ON DELETE RESTRICT ON UPDATE CASCADE
);
